server:
  port: 8888
spring:
  application:
    name: spring-cloud-nacos-gateway-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          version: 2.0